spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.60.146.47:1521:yctest
    username: vasdba
    password: vasdba
    hikari:
    maximum-pool-size: 80