server:
   port: 8888
logging:
   config: classpath:logback.xml

application:
        name: router
registry:
        address: zookeeper://127.0.0.1:2181
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.60.146.47:1521:yctest
    username: vasdba
    password: vasdba
    hikari:
    maximum-pool-size: 80
  cache:
    ehcache:
      config: classpath:ehcache.xml
mybatis:
  mapper-locations: classpath*:com/example/testyc/persistence/**/*.xml

